### ISSUE TITLE
Erro ao tentar editar o bairro e na finalização do pedido.

### ISSUE THREAD

**Issue by nathampa0909** [CaduGimenes/vendas#3]
Boa noite!

Estou com dois erros: 
Finalização do pedido: http://prntscr.com/o35atu 
Ao tentar editar o bairro: https://hastebin.com/axaceyaqej.js

**Comment by CaduGimenes** [comment]
Boa tarde!

Em relação ao erro da **finalização dos pedidos** (https://prnt.sc/o35atu), é necessário ter uma impressora fiscal conectada ao seu computador, para  assim, conseguir gerar a nota, e também a comanda, mas sinta-se a vontade para implementar a impressão em papel A4, e um pull request!

Poderia me dar mais detalhes em relação ao erro de edição de bairros? Logo estarei disponibilizando o ambiente em Docker, para assim diminuir a possibilidade de problemas.

Estarei aguardando o seu contato, obrigado por reportar essa issue :)

**Comment by nathampa0909** [comment]
Boa noite!

Acho que o hastebin deu algum problema. https://pastebin.com/Q84pKKR4

O erro acontece quando eu clico pra tentar editar um bairro, redireciona porém dá o erro do pastebin acima.

Desculpe sobre o da finalização, estava mexendo desde ontem e aí fui entender realmente a finalização do pedido. Ainda sou iniciante em PHP, estou fazendo um crud para os clientes assim como os bairros, caso eu consiga descobrir algo mando um pull request e/ou mando o erro aqui.

Agradeço a atenção.

**Comment by nathampa0909** [comment]
Fiz um trabalho para uns caras e dê uma olhada como fiz o crud dos clientes: https://github.com/gomesbreno/vendas , não concertei o dos bairros, tentei fazer o dos clientes assim como o dos bairros e dava o mesmo erro: Undefined index. Creio que seja algum problema com os getters e setters. Não tenho muita experiência com PHP, aprendi mesmo editando esse projeto, porém não consegui ver o problema do crud dos bairros, tanto que fiz o dos clientes mais direto.

**Comment by nathampa0909** [comment]
Ahh, comentei também a parte do código da impressora fiscal e fiz uma página de finalização do pedido, ficou bem básico.

**Comment by CaduGimenes** [comment]
Olá @nathampa0909,

Ao analisar o Controller/ClientController.php, na linha 61
` Client::updateAddress($cd_cliente, $_POST["nm_logradouro"], $_POST["nm_cliente"], $_POST["nr_casa"], $_POST["nm_bloco"], $_POST["cd_bairro"]);` 

O método "updateAddress", está sendo chamado estaticamente, porém ele não foi definido como tal.

`        public function updateAddress($cd_cliente, $nm_logradouro, $nm_cliente, $nr_casa, $nm_bloco, $cd_bairro){
`

Como pode ver no arquivo Model/Client.php, na linha 76, o método foi declarado como publico e não estático, ao tentar executar o mesmo ele ira retornar um erro, tente declarar da seguinte maneira:

` public static function updateAddress($cd_cliente, $nm_logradouro, $nm_cliente, $nr_casa, $nm_bloco, $cd_bairro){
`

**Comment by CaduGimenes** [comment]
Olá, @nathampa0909,

Realizei um clone no seu fork, e descobri o porque dos erro na view de alteração dos bairros
![image](https://user-images.githubusercontent.com/32314620/60688642-dbb20d80-9e8c-11e9-8ee1-b1ba58658c34.png)

Na linha 21, a rota está sendo passada com o parâmetro `cd_frete`:
`        <form action="/district/update/{$district.cd_frete}" method="POST">
`
Quando na verdade o array que retorna as informações do bairro, traz o id, com o nome de cd_bairro:
`Array ( [cd_bairro] => 6 [nm_bairro] => Anhanguera [vl_frete] => 2.00 )`

Para corrigir este problema, basta substituir o `cd_frete` por `cd_bairro`
![image](https://user-images.githubusercontent.com/32314620/60688746-7dd1f580-9e8d-11e9-99f4-a99a6e8bdd09.png)

Ao alterar a rota o programa funcionara normalmente.
![screencapture-localhost-district-update-6-2019-07-04-18_57_43](https://user-images.githubusercontent.com/32314620/60688788-ae199400-9e8d-11e9-8996-e0e12f39eeb6.png)

Desculpe pela demora, fique a vontade para mandar mais duvidas, todas serão bem vindas! 🥇
